NetperfRunner:
  log_path: /tmp/netperf_result
  exe_time: 60
  instance:
    - 1
  rounds: 5
  data_modes:
    - TCP_STREAM
    - TCP_RR
    - TCP_CRR
    - UDP_STREAM
    - UDP_RR
  rr_size:
    - 32, 32
    - 64, 64
    - 128, 128
    - 256, 256
    - 512, 512
    - 1024, 1024
    - 2048, 2048
    - 4096, 4096
    - 9000, 9000
    - 16384, 16384
    - 32768, 32768
  m_size:
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 1460
    - 2048
    - 4096
    - 9000
    - 16384
    - 32768
